sudo: required
dist: trusty
language: php
php:
  - 7.0
  - 7.1
before_script:
  - composer install
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

install: travis_retry composer update --prefer-dist

script: ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) 

notifications:
